### ISSUE TITLE
ASCII conversion ignores multiple chained smileys like :):):)

### ISSUE THREAD

**Issue by hachre** [emojione/emojione#395]
If you run `emojione.toImage(":):):)");` the conversion isn't applied. There have to be spaces in between the smileys currently, which is not ideal.

![screenshot](https://cloud.githubusercontent.com/assets/885304/20518690/5062e178-b0a0-11e6-881e-511bd30ce6c6.png)

**Comment by caseyahenson** [comment]
@hachre we do have plans to improve the functionality of the ASCII replacement process, but so far in our testing the best solution has been to use a space as a delimiter for ASCII chars since it can be clunky to attempt the deciphering of characters otherwise. Hopefully in the near future we'll be able to get a comprehensive fix/improvement pushed out for this.

**Comment by caseyahenson** [comment]
In the 3.0.4 patch we added the property `riskyMatchAscii` which will attempt to resolve this issue. Setting to `true` will disable the encapsulating space requirement, but can also cause unexpected results.
