### ISSUE TITLE
Why fonts are not supported by Chrome?

### ISSUE THREAD

**Issue by ovr** [emojione/emojione#441]
Hey!

https://github.com/Ranks/emojione/blob/master/assets/fonts/README.md

> sing these fonts with Firefox or Microsoft Edge, you can enjoy full-color EmojiOne emoji

but why it's not working with Chrome?

**Chromium v.56**
![image](https://cloud.githubusercontent.com/assets/4124371/23888993/d1112afc-089b-11e7-9d17-f0c2e04109c4.png)

**Firefox v.52**
![image](https://cloud.githubusercontent.com/assets/4124371/23889027/02061b72-089c-11e7-8485-ffe9fcd54aef.png)

Looks like I find a possible related comment:

refs https://github.com/eosrei/emojione-color-font/issues/57

![image](https://cloud.githubusercontent.com/assets/572096/23932250/2bf5adc4-097a-11e7-8a0c-2c13a081adc6.png)

Maybe someone of creator can regenerate fonts with CBDT (or similar thing that supported in Chrome)?

cC @caseyahenson @miguelsousa @thinkrick @mikebe11 @eosrei 

Thanks

**Comment by Crissov** [comment]
- COLR/CPAL:
  * https://github.com/mozilla/emojione-colr
  * https://github.com/fonttools/fonttools
- CBDT/CBLC:
  * https://github.com/googlei18n/noto-emoji
  * https://github.com/googlei18n/nototools
  * https://github.com/behdad/color-emoji
  * https://github.com/fonttools/fonttools
- SVG:
  * https://github.com/adobe-type-tools/opentype-svg
  * https://github.com/fonttools/fonttools
- sbix:
  * https://github.com/fonttools/fonttools

(incomplete list)

**Comment by maximbaz** [comment]
Hey @caseyahenson, with a pure luck I noticed that you uploaded [emojione-apple.ttc](https://github.com/Ranks/emojione/blob/754b3f0d7f7b45656114a9bf69259e77f0246dc0/extras/fonts/emojione-apple.ttc) a couple of days ago, and you managed to create this file in a way that it also brings colorful emojis for Chrome on Linux, for the very first time! Until now, EmojiOne set was available only in black and white for Chrome users on Linux via [emojione-svg.otf](https://github.com/Ranks/emojione/blob/693a9705f60efd566e40a5c9ec00ca306c9bcbd0/extras/fonts/emojione-svg.otf), but you changed this 🎉 

There's just one problem I'm hoping if you could help me solve before we could announce that colorful emojis are finally available for other Linux users.

The glyphs in both `emojione-apple.ttc` and `emojione-apple.ttf` are positioned too high comparing to the letters in all other fonts. This issue is not present in the `emojione-svg.otf`, as I'll show in the screenshots below. 

Could you please generate an additional font file for Linux users with adjusted offset? Both `ttc` and `ttf` extensions are supported on Linux, we just need one of them, doesn't matter which. I can't tell you exactly which offsets are different between `ttc` and `otf` fonts (because I don't know how to check this), but I am willing to provide you any help I can. We could also sync on any chat platform if you want, to make things quicker.

I'd be _extremely_ grateful if you could help with this, as I'm sure many other Linux users! We are one step away from having colorful emojis in Chrome on Linux 🎉 

![image](https://cloud.githubusercontent.com/assets/1177900/25319598/fee5c0ae-289f-11e7-921b-4ddafcabd5c6.png)

![image](https://cloud.githubusercontent.com/assets/1177900/25319638/48131d94-28a0-11e7-8c36-aa21be384cf6.png)

**Comment by maximbaz** [comment]
I attempted to use https://github.com/fonttools/fonttools suggested by @Crissov to modify the ttf font, but this is where my luck stopped: I simply can't find how to move the glyphs down. Whatever I change, ascents, descents, heights and what not, the glyphs are just not moving down 😞 Well, not exactly true, the only way I found that moves them down is by adjusting `originOffsetY` on:

```
<glyph graphicType="png " ... originOffsetX="0" originOffsetY="0">
```

However this seems to be adjusting in absolute coordinates (whatever they are), i.e. on a large font size it feels like glyphs need to be moved further down, while on a small font size it feels that they are already down too much... What is the proper way to center glyphs on the line? 🤔

By the way, @caseyahenson with the current `emojione-apple.ttf` font, are the glyphs actually centered on Apple devices, not too high like on my screenshots above? Ideally I'd like to find a way to make apple font work on both Apple and Linux devices, so that we have less ttf fonts to maintain 🙂

**Comment by maximbaz** [comment]
@pw5a29, @vXBaKeRXv, I just noticed that you are acknowledged for creating Apple font for EmojiOne. Could you please have a look at the issue above, if this is something you could suggest how to solve?

**Comment by maximbaz** [comment]
@m13253 mentioned in another thread that Android font actually works fine on Linux too, and in fact it is positioned correctly, just like the SVG font.

I'd still recommend to double check how Apple font looks on Apple devices, whether it needs position adjustments or not. It clearly has a different positioning than Android and SVG fonts, which is suspicious.

But looks like there is nothing left to do for Chrome on Linux, it works 😉

**Comment by m13253** [comment]
> Android font actually works fine on Linux too

You can also install a patched Cairo library to display color emoji in all Gtk+ applications (not only in Chrome).
These are packages with the patch:
- https://aur.archlinux.org/packages/cairo-coloredemoji
- https://software.opensuse.org/package/libcairo2-color-emoji

**Comment by maximbaz** [comment]
Wow, thanks! :+1:

**Comment by vXBaKeRXv** [comment]
Hey, they must have added support.... 
I don't have chrome on my Linux setup because the distro is old.
VM buggy 


To move it up or down: Adjust the **Y contour** in the 'glyf ' table.

**Example with Notes++** 
![untitled](https://cloud.githubusercontent.com/assets/8807796/25563826/7adca112-2d61-11e7-9776-c431d72a399b.png)
![untitlewd](https://cloud.githubusercontent.com/assets/8807796/25563827/7c7be866-2d61-11e7-8f68-47429f432c37.png)


I helped mitch a little with emojitools so it could compile a sbix font. 
Universal font maker! lol

**Comment by maximbaz** [comment]
Thanks for your suggestion @vXBaKeRXv!

I've just tried, unfortunately it makes no difference, whether I change `y` to `-500` or `500` in the shown contour, the glyphs remain on the same level...

**Comment by vXBaKeRXv** [comment]
It should be moving around... Maybe it don't fully support it yet.
To adjust left or right I mod the 'htmx' table. 
Its something ive done before making a iOS keyboard font with sbix. 
Took me forever to understand how to move the embedded image up or down. 

![untitled](https://cloud.githubusercontent.com/assets/8807796/25570739/07b03c7e-2de5-11e7-927c-ce5d26020390.png)

http://www.mediafire.com/file/cvnvs30xb5vrcd2/lowertestACE.zip

**Comment by maximbaz** [comment]
Hm, at this point I can only assume that Linux somehow doesn't respect the Y contour on the 'glyph' table. This is very unfortunate, I imagine Linux uses some other parameter to position glyphs (and Android, since Android font is centered on my laptop). 

But this is how your Apple font looks on my box:

![image](https://cloud.githubusercontent.com/assets/1177900/25587572/f2033550-2ea4-11e7-850d-afb8a855795a.png)

 But thanks anyway!

**Comment by vXBaKeRXv** [comment]
Yep it looks like it don't read it.  
The apple emoji has 'hmtx' and 'vmtx' tables but the 'vmtx' does nothing when I adjust it. If I can remember right.  
I wonder if they are using that instead?!? 
Notocoloremoji don't use the 'glyf ' table. 

Your welcome, np!
Its really cool seeing them add support for colored fonts. 
Hopefully others will follow along.

**Comment by maximbaz** [comment]
I've just tried adjusting the `vmtx` table, it also has no effect 😕

Anyhow, now at least I know why fonts are not provided officially - it requires true magical skills to properly build one 😄

**Comment by maximbaz** [comment]
To give a final update, I solved the issue with the Android font which I modified to use the v3 assets. 
It is positioned perfectly on Linux. See https://github.com/Ranks/emojione/issues/477#issuecomment-298794910 if you are interested in getting the font.
