### ISSUE TITLE
EmojiOne 3.0 Android font file

### ISSUE THREAD

**Issue by DeicPro** [emojione/emojione#477]
Is there some way to build it?

**Comment by Crissov** [comment]
https://github.com/behdad/color-emoji [etc.](https://gist.github.com/Crissov/597d60535d8b3f104a4ef616db887534)

**Comment by DeicPro** [comment]
@Crissov instructions not clear. What are the exact steps to build a working NotoColorEmoji.ttf font file for Android?

**Comment by Crissov** [comment]
Find the required PNGs over at the new [emojione-assets repository](https://github.com/Ranks/emojione-assets/).
Possibly rename them using Emoji-Tools.
Build a font file with `emoji_builder.py` and `add_glyphs.py` from the ["color-emoji" repo](https://github.com/behdad/color-emoji). Use [Noto Emoji](https://github.com/googlei18n/noto-emoji/blob/master/Makefile) or the [example Makefiles](https://github.com/behdad/color-emoji/blob/master/examples/PhantomOpenEmoji/Makefile) for reference.
Possibly edit the font file with [fonttools](url).

> Usage:
> `emoji_builder.py [-V] [-O] [-U] [-A] font.ttf out-font.ttf strike-prefix...`
> This will search for files that have strike-prefix followed
> by a hex number, and end in ".png".  For example, if strike-prefix
> is "icons/uni", then files with names like "icons/uni1f4A9.png" will
> be loaded.  All images for the same strike should have the same size
> for best results.
>
> If multiple strike-prefix parameters are provided, multiple
> strikes will be embedded, in the order provided.
> The script then embeds color bitmaps in the font, for characters
> that the font already supports, and writes the new font out.
>
>If -V is given, verbose mode is enabled.
>If -U is given, uncompressed images are stored (imageFormat=1).
>By default, PNG images are stored (imageFormat=17).
>If -O is given, the outline tables ('glyf', 'CFF ') and
>related tables are NOT dropped from the font.
>By default they are dropped.
>If -C is given, unused chunks (color profile, etc) are NOT
>dropped from the PNG images when embedding.
>By default they are dropped.

**Comment by DeicPro** [comment]
@Crissov that was helpful, thanks you. I will try luck :)

**Comment by morealaz** [comment]
Is there going to be an official android font release like apple one's?

**Comment by caseyahenson** [comment]
We'll be looking to the community to contribute an Android font with our 3.0 artwork. We're willing to help by providing any assets needed for this.

**Comment by maximbaz** [comment]
With [Emoji-Tools](https://github.com/MitchTalmadge/Emoji-Tools) there is a pretty easy way to update the artwork for the [current font](https://github.com/Ranks/emojione/blob/693a9705f60efd566e40a5c9ec00ca306c9bcbd0/extras/fonts/emojione-android.ttf). I could basically unpack the font with that app, replace all _existing_ png with images from [emojione-assets](https://github.com/Ranks/emojione-assets/) and pack it back. 

There is a catch though, a pretty upsetting one. The [emojione-assets](https://github.com/Ranks/emojione-assets/) has 2427 images, and out of those 625 did not exist in the original font, and I don't know (yet) how to add them (if I simply put extra png in the folder, it will corrupt the font entirely). This probably means a lot of new emojis are not present in the font.

Still, from the first glance the font seems to work fine on my Linux, the most common emojis are there. I'll be testing it during the following days. Does anyone want to try it on Android? 

[(Download: emojione-android.ttf)](https://github.com/maximbaz/dotfiles/blob/50fb785dd022fb3c1a4625b87483ad61b6681c7e/.local/share/fonts/emojione-android.ttf)

**Comment by Lokesh-Krishna** [comment]
Tested it on Android 7.1.1, using both, the AOSP keyboard and GBoard.
I couldn't find any emoji missing so maybe it supports all the emoji that Android itself does presently and to add the one that aren't there without a means to input them would be pointless.
Thank you so much! Loving it!

**Comment by morealaz** [comment]
I personally try [Emoji-Tools](https://github.com/MitchTalmadge/Emoji-Tools) for creating android-font, and got same problem as @maximbaz said. I also tested [color-emoji](https://github.com/behdad/color-emoji), but scripts complaining about some emoji's which have long name's like **1f6b4-1f3ff-2640** one for example. It seems that [add_glyphs.py](https://github.com/behdad/color-emoji/blob/master/add_glyphs.py) and [emoji_builder.py](https://github.com/behdad/color-emoji/blob/master/emoji_builder.py) need to be changed and modified.

**Comment by maximbaz** [comment]
@caseyahenson do you want me to create PR with the font? 

Like I mentioned it doesn't have all icons, but it is not worse than the currently provided font, it has exactly the same number of emojis, only with v3 assets 🙂

**Comment by caseyahenson** [comment]
@maximbaz that would be great, thanks! We'll still be on the lookout for a contributor to help out with adding the remaining Emoji 4.0 set (the 600 and some missing as you pointed out) but at least having v3 assets in place of v2 is a big improvement.

**Comment by maximbaz** [comment]
The PR is out. Let's keep this issue open until we get the missing emojis in the font, as some attempts and experience was already shared here (perhaps only rename the issue).

#### To the future contributor who will add missing icons: 

Please describe how exactly you achieve that, as detailed as possible. 
It would be of a great help to spread this knowledge. 

Whether the solution is to add missing glyphs or regenerate the whole file, with such info we could even come up with a (partially) automated script to keep the font up to date with changes in [emojione-assets](https://github.com/Ranks/emojione-assets/).

**Comment by vXBaKeRXv** [comment]
EmojiTools has a java memory problem with building big noto emoji fonts. 
Mitch was planning to remake it without java if possible. It cant handle renaming the latest emoji sequences. It varies across each emoji set I come across so it makes porting tricky.  

Did you only rename the assets to (u prefix) before building? 
When I decompile the android-emojione with ttx tools the glyphID names are corrected to Unicode.  
FontTools/TTX sort of does this with cmap and gsub tables but don't fully convert them to a alternate name.  I don't fully understand how its getting rebuilt like that and witch tool/scripts are being used... 

The latest 'color-emoji' project is located here. I cant get the noto-emoji tools to work right either. 
https://github.com/googlei18n/noto-emoji/tree/master/third_party/color_emoji

If you have the latest FontTools ttx tool you can try this route.. 
[ ttx.py -s -z extfile font.ttf ]
Replace the images and compile it back up like a normal ttx file. 

I don't have setup to run a android emoji.  I have ben helping RickyBush with his porting/sharing on xda. 
To rename all the assets to match exactly like stock notoemoji I use my own python script but its to embarrassing for me to share because its messy and coded bad.  
http://www.mediafire.com/file/yyvtfw9tdlo6owy/emojione+android+128.zip

**Comment by maximbaz** [comment]
I'll share my experience. I tried the following:

* Unpack the emojione-android.ttf with EmojiTools, it creates the folder `ExtractedEmojis` with a bunch of images and a ttx file.
* The images have `uni` prefix, for example `uni270d_uni1f3ff.png`.
* I take one (only one, for the sake of precise experiment) image of a new emoji from emojione-assets. To be precise, I took [woman golfing](http://emojipedia.org/woman-golfing/). It was called `1f3cc-2640.png`, I rename it according to the pattern to `uni1f3cc_uni2640.png`.
* Now I use Emoji-Tools to pack this font back. 

First I hoped that the new image will be automatically embedded, but no, it doesn't happen. I don't see any OutOfMemory issues, but the image is simply ignored:

```
May 04, 2017 10:24:48 AM com.mitchtalmadge.emojitools.LogManager logInfo
INFO: Skipping uni1f3cc_uni2640.png
```

When I dig into the code, I see that this happens because:

1. The `uni2640` is not defined in `<cmap_format_12>` table.
2. The `<LigatureSet` for the given pair is not defined.

Then I tried to manually edit `ttx` file:

https://gist.github.com/maximbaz/17e670b496475b967c406f3837dec64c

But still cannot build, it fails on the very last stage, when running `ttx` tool, with the following stack trace:

```
  ...
  File "/home/maximbaz/private/Emoji-Tools/target/tmp/PythonScripts/fontTools/ttLib/tables/_c_m_a_p.py", line 89, in compile
    chunk = table.compile(ttFont)
  File "/home/maximbaz/private/Emoji-Tools/target/tmp/PythonScripts/fontTools/ttLib/tables/_c_m_a_p.py", line 767, in compile
    raise KeyError(name)
KeyError: u'uni2640'
May 04, 2017 11:37:27 AM com.mitchtalmadge.emojitools.LogManager logSevere
SEVERE: AN ERROR HAS OCCURRED!
```

And at this stage I stopped, I don't know how to proceed.

**Comment by vXBaKeRXv** [comment]
The last android-emoji.ttf was built using other tools.  I think noto-emoji tools...  Never mind about the U prefix question.  

Memory problem happens when you compile a big file. Example: If you tried to wright the appleemoji images inside a notoemoji it will output that error. 

EmojiTools is using a older add_glyph.py... Its searching to add sequences in based on the image names and cant find a match.  I could be wrong though. Im not to sure if he has the same email the logs get routed to. You can try and contact him here. Last time I heard from him he had to get back to school work. 
https://twitter.com/mitchtalmadge?lang=en


This is the two best options I know of. 
1)
 Grab a Stock notocoloremoji.ttf and just replace the images inside that using EmojiTools and edit the font tables a bit if you want to use 128x128.  

2) 
Use Noto-Emoji Tools to rebuild notocoloremoji.ttf. 
I ran into a problem and haven't touched it in awhile.

**Comment by Crissov** [comment]
Let's ping @MitchTalmadge then.

**Comment by MitchTalmadge** [comment]
Wow, sorry guys! I did not know this thread existed. I've had hardly any time to work on Emoji Tools recently. As an engineering student, I barely have time to even sleep. College just got out, though, so I'll see what I can do to help. Let me look over this and I'll let you all know what I find.

**Comment by MitchTalmadge** [comment]
@maximbaz I was able to successfully add the woman golfer to the font, package it, and unpackage it. Here are the diffs:
https://gist.github.com/MitchTalmadge/fe945de575771831e25a784a29f89cdf

Key differences:

- Even though uni2640 does not have an image association, it still must be defined as a glyph.
- You must add the "cbdt_bitmap_format_17" for "u1F3CC_uni2640" in order for Emoji Tools to be able to put in the image data. My program expects this xml to already exist (it essentially just replaces the existing bytes in the file.) I know this is sucky, but I never got around to finishing it.

Hope this helps. I do want to add support for adding new emojis soon. It's difficult though, as you can see. Lots of places to mess up.

**Comment by maximbaz** [comment]
Wow, nice job @MitchTalmadge!

How far do you think is your tool from being able to add new emojis? Initially I was thinking to draft some script to do these steps, but having your tool would be a way more secure approach (it is truly easy to mess up, I agree).

**Comment by MitchTalmadge** [comment]
I could probably implement it into the existing Emoji Tools with a few days of work, but I think it'd be more beneficial in the long run to just keep working on the new Emoji Tools and integrate it within that. I don't have a time estimate for the completion of the new Emoji Tools, so I'd encourage you to try your scripts until I can get something better working :)

P.S. I think I don't use the add_glyphs.py script in my tools. The file is there but I don't believe I ever used it, in case you were curious.

**Comment by MitchTalmadge** [comment]
BTW, to contact me: https://mitchtalmadge.com/contact/ or DM me on Twitter

**Comment by maximbaz** [comment]
I had time to play a bit more, and I already hit the next roadblock 🙂 

Using your gist I can package now the font with the `woman golfing` image (called `uni1f3cc_uni2640.png`). However, after installing the font, the `woman golfing` is still not being rendered properly, i.e. I see it as two characters, a golfer and a female sign.

I also noticed that the Codepoints section for `woman golfing` on [emojipedia.org](http://emojipedia.org/woman-golfing/) is different, according to the website, the image file should be called `uni1f3cc_unife0f_uni200d_uni2640_unife0f.png`. 

I tried that as well, renamed the image file and adjusted the `Ligature component` from 

    <Ligature components="uni2640" glyph="u1F3CC_uni2640"/>

to 

    <Ligature components="uniFE0F,uni200D,uni2640,uniFE0F" glyph="u1F3CC_uni2640"/>

... and this compiled as well, but doesn't render the emoji either!

----

So I'm confused, can we not trust the image names in [emojione-assets](https://github.com/Ranks/emojione-assets/), or why the Codepoints are different? 
And how come the emoji is not being rendered? 😕

**Comment by caseyahenson** [comment]
Awesome to see everybody pitching in here to get this font put together! @maximbaz the correct output for those is found in the emoji.json file. That data is structured with what we refer to as the "base codepoint" (stripped of ZWJ and VS16) as the key, and you can map the filenames to the `code_points.output` property using the file names found in the emojione-assets directory as the base codepoint. 

Or, that link that @vXBaKeRXv posted in his earlier comment (http://www.mediafire.com/file/yyvtfw9tdlo6owy/emojione+android+128.zip ) has the 128px images named to what appears to be a fully qualified format.

**Comment by maximbaz** [comment]
Cool, thanks, emoji.json would certainly help 🙂 However the bigger problem remains, even with the correct codepoint the font doesn't render "woman golfing".

Could someone try as well, just to make sure the problem is not with my particular computer? @Lokesh-Krishna perhaps?

See how [woman golfing](http://emojipedia.org/woman-golfing/) is rendered, before and after installing this new font: [Download](https://github.com/maximbaz/dotfiles/raw/74cce46951f34f6a42535f40901d6f410455a7c1/.local/share/fonts/emojione-android.ttf)

**Comment by vXBaKeRXv** [comment]
Mitch makes his own add_glpyh.py. using java. This peace is important when it comes to rebuilding a font with added glyphs.  

The image data for the female symbol is not written in the CBDT table, and the LigatureSet glyph is missing from the GSUB.  

Apple or Noto emoji its a pain to add new glyphs into the font. This is what your are trying to do vs swapping the images in font.  If you plan on just swapping and using 128x128 you need to fix values in the CBDT and metrics.

That last android emoji was made using other tools or a mix of tools. I believe Noto-Emoji Project..

**Comment by MitchTalmadge** [comment]
@maximbaz I feel like maybe Android just doesn't have the support for rendering that particular emoji, like the keyboard doesn't support it or something. How are you "rendering" the emoji? Copy and pasting from emojipedia?

If it helps, I finished Android Emoji extraction on my new Emoji Tools rewrite, and the emoji font you provided does properly extract:

![image](https://cloud.githubusercontent.com/assets/8848080/25790561/ed6742b2-3376-11e7-80c9-73abb5da2458.png)

So I think it's fine in the ttf.

**Comment by maximbaz** [comment]
@MitchTalmadge I think we shouldn't confuse typing emoji and rendering them, even if a particular device doesn't have that emoji on their keyboard, they should be able to render this emoji when someone else sends it to them. And according to emojipedia, Google and others can render that specific emoji on their default fonts (there are pictures how Google and others are supposedly rendering them).

In my particular case however, I'm using this font on the desktop Linux 🙂 

I want to be able to render all emojis that are sent to me from other devices. That includes the emojipedia page, I want to see that glyph rendered properly. I'm sending emoji primarily in a chat application, where they have an emoji autocomplete, matching emoji name to their Unicode symbols. And just like on emojipedia, emojis like `woman golfing`, `woman biking` and `woman astronaut` are not rendered as one symbol.

**Comment by maximbaz** [comment]
Let's test again on both mobile and desktop devices when your new tool is able to include these new emojis, I think I'm just missing something there when building the font by hand.

**Comment by vXBaKeRXv** [comment]
To add emoji/glyphs to the system is supper complex stuff.  The device might not recognize it or join the sub ligatures using the grapheme process ect.  Some sites like Emojipedia can handle it fine ok in most places.  We use a mod to get backwards support on iOS.

**Comment by vXBaKeRXv** [comment]
Mitches emojitools cant add in sub glyphs yet. This could be the problem...  I inspected that emojione noto a little more and it might be built using something other than noto-tools and emojitools, the font is tagged with Adobe instead of Google inc. 



These are a hit and miss when it comes to support on a android device. 
Google, Samsung, LG  ect. 
![untisstled](https://cloud.githubusercontent.com/assets/8807796/25995307/ece89f38-36ce-11e7-9b15-3c89878e8852.png)

Emojis that use more than one person/body part in a single code is being rejected. Android 7.1.1 was created before that was proposed .
These don't exist in EmojiOne image set . 'COMBINING ENCLOSING KEYCAP' (U+20E3) and the Question mark AY Flag.
![untitled](https://cloud.githubusercontent.com/assets/8807796/25995368/34f1f504-36cf-11e7-9434-b9de43eb737d.png)

**Comment by mxalbert1996** [comment]
I think it's quite easy to build EmojiOne Android version using the building scripts of [NotoColorEmoji](https://github.com/googlei18n/noto-emoji). I build one and it works well for me.
You can find my modified building scripts [here](https://github.com/mxalbert1996/emojione-android). There is also a build in `fonts` directory.

**Comment by maximbaz** [comment]
Wow, @mxalbert1996 you rock! :+1: 

I installed the font from your repo and on my Linux it correctly renders all glyphs, even the newest `woman golfing` and others! 

Would you create a PR and submit your font in this repo as well? I can also do that, if you are busy.

Place to put it: [link](https://github.com/emojione/emojione/tree/master/extras/fonts)

**Comment by antonywalker** [comment]
I'd like to add that the font from @mxalbert1996 also renders all glyphs on my OnePlus 3T running Android 7.1.1.

Thank you, everyone.

**Comment by maximbaz** [comment]
By the way, the website also needs an update, it still says "Android font v2.3": https://www.emojione.com/developers/download

**Comment by caseyahenson** [comment]
Thanks @maximbaz great catch, we'll get that updated.

**Comment by DeicPro** [comment]
Emoji like ☠⛑❤❣ etc.. are ASCII (idk if are called so)

and cut.

**Comment by maximbaz** [comment]
The font is fine. Are you on Linux? Take my [fontconfig](https://github.com/maximbaz/dotfiles/blob/b63b2fe4bb5362d207e407c646655070cd1251bc/.config/fontconfig/conf.d/70-emojione-color.conf), clear cache with `$ fc-cache -f`, then try again.

[Emojipedia](http://emojipedia.org/heavy-black-heart/) is a good place to test, they correctly define font family.

![image](https://cloud.githubusercontent.com/assets/1177900/26515410/cd6394f8-427a-11e7-87d9-efab536a4c5e.png)

**Comment by DeicPro** [comment]
@maximbaz I'm on Android
![img_20170527_012427](https://cloud.githubusercontent.com/assets/12710770/26515488/798f0ece-427b-11e7-896e-3b80b23b80a7.jpg)

**Comment by maximbaz** [comment]
Huh, then I'm totally puzzled. Contrary to Linux, on Android there should be literally zero configuration required (or I thought so). I don't have an Android device at the moment, perhaps someone else from this thread could give you a hint.

But the font itself is most certainly fine, as you can see I use it without problems, also I don't see them as cut-off in the bottom. I think there is some extra step or configuration that you are missing.

![image](https://cloud.githubusercontent.com/assets/1177900/26515582/5907a7dc-427c-11e7-8ec9-d0abfb5f5f40.png)

**Comment by DeicPro** [comment]
I will check if exists some separate cached files of emojis in /data or something...

The cut-off isn't in all places, in some place is complete, in another doesn't.

YouTube app for example:
![img_20170527_014227](https://cloud.githubusercontent.com/assets/12710770/26515723/d97f31ea-427d-11e7-920f-1409fce73135.jpg)

I think that this hasn't solution, is a YouTube problem in this case not EmojiOne.

**Comment by mxalbert1996** [comment]
@DeicPro I think the first problem might be because there are other fonts before Emojione in your font fallback list which include the glyphs and there is no Unicode Variation Selector(`U+FE0F`) after the emoji. For example, on my phone, ☠⛑ renders as monochrome but ☠️⛑️(adding `U+FE0F`) renders well. You can use Chrome to open https://en.wikipedia.org/wiki/Emoji and see if the emojis can be displayed. On my phone all emojis rendered well except ©®‼⁉™ (it's probably because of the way Android handles `U+FE0F`).
I don't have the second problem on my phones. Is it because you are using an unusual DPI setting?

**Comment by DeicPro** [comment]
@mxalbert1996 removing `NotoSansSymbols-Regular-Subsetted.ttf` fix the problem, but I think I lost some emoji symbols, but I don't care.

My DPI is 480... is a very common DPI for 5'5 inch 1080p display.

**Comment by vXBaKeRXv** [comment]
Cut off problem is kind of common on android from what I see. They added in vmtx table to new Android O emoji, I assume it might be a partial fix.  Someone narrowed it down to the coded views within the system. https://github.com/emojione/emojione/issues/404

**Comment by vXBaKeRXv** [comment]
@mxalbert1996 Good work on getting that emojione noto project together.  If you built your Makefile into a Python script it will be faster and more cross platform. I think compressing images should be a option and some use other tools like "CompressImages.py". I have a narrow Python 2.7 build so it runs into Unicode problems on Windows and Makefiles with Cygwin still hectic. Latest noto-tools fixed narrow build problem but the builder sctipt by behdad still runs into that error. Stuck using Linux to build but it's supper slow.

**Comment by DeicPro** [comment]
ok, reading `/system/etc/fallback_fonts.xml` I understand how to works. It is legacy to old apps, the new fallback fonts file since Android L is `/system/etc/fonts.xml`, so I moved to the first position (under `familyset` tag) `NotoColorEmoji.ttf` in `fallback_fonts.xml` to got compatibility with legacy apps and place in the first position (under `<!- fallback fonts ->` comment) in `fonts.xml` too.

Now I have got all emojis and symbols properly working, except `‼`, `⁉`, `©`, `®` and `™` like you.

**Comment by DeicPro** [comment]
Too I see a tag in `fonts.xml`:
`<font weight="400" style="normal">`

Changing the weight value fix the cut-off problem.

**Comment by mxalbert1996** [comment]
@DeicPro Then the problems should be the bugs of old Android versions (although they were probably not bugs at that time). In Android N, there is no more `fallback_fonts.xml` and NotoColorEmoji has been moved to the front of NotoSansSymbols like this:
```XML
    <family lang="und-Zsye">
        <font weight="400" style="normal">NotoColorEmoji.ttf</font>
    </family>
    <family>
        <font weight="400" style="normal">NotoSansSymbols-Regular-Subsetted2.ttf</font>
    </family>
```

**Comment by antonywalker** [comment]
I've noticed a similar problem with the Frowning Face emoji.

It only came to my attention when I received a WhatsApp message, and in the notification the emoji was displayed as a glyph. I can, indeed, insert the emoji myself- which displays correctly on all of the messaging apps I have, yet it seems to render as a glyph at a system level.

Example 1:
![](https://dl2.pushbulletusercontent.com/eTXPhhXKDmdwyNwwuJZm14V9rqhSWyHk/Screenshot_20170605-015553.png)

Example 2:
![](https://dl2.pushbulletusercontent.com/KjVdu5Qq9k1PbJ5IWZDhKj3JDjUbeZtG/Screenshot_20170605-015605.png)

Also: I've tried it with other emojis from the NotoColorEmoji font file, with it still rendering as above.

**Comment by mxalbert1996** [comment]
@antonywalker I rechecked the `fonts.xml` of Android N and found that `NotoSansSymbols-Regular-Subsetted.ttf` which includes the monochrome version of Frowning Face(U+2639) is before `NotoColorEmoji.ttf`. Put it after `NotoColorEmoji.ttf` might solve the problem.

**Comment by antonywalker** [comment]
@mxalbert1996, thanks for your advice.

I was hoping that doing so would solve the problem as it has above- which it did, but only partially.

As you can see, the emoji now displays properly here:
![1](https://cloud.githubusercontent.com/assets/16846349/26783672/46ae1e5a-49f1-11e7-80cf-b26364476e5f.png)

The monochrome version, however, still rears its ugly head in the notification drawer:
![2](https://cloud.githubusercontent.com/assets/16846349/26783696/6cbab3ba-49f1-11e7-8cfb-a53e39f90c76.png)

Just to check, I also repositioned the font in fonts_slate.xml. No luck, sadly... What I then realised was that I had recently changed my system font to the new OnePlus 'Slate' font. Once I reverted back to Roboto, all is well.

I'll do some experimentation with the 'Slate' font in a while to see why this is happening.

**Comment by DeicPro** [comment]
@antonywalker check my previous comment https://github.com/emojione/emojione/issues/477#issuecomment-304511210

**Comment by antonywalker** [comment]
@DeicPro, as was also recommended by @mxalbert1996, I did edit the fonts.xml file. The aforementioned issue is still present.

**Comment by DeicPro** [comment]
@antonywalker but @mxalbert1996 said before NotoSansSymbols-Regular-Subsetted.ttf, I said before all font after `<!- fallback fonts ->` comment in `fonts.xml`. Did you try it?

**Comment by antonywalker** [comment]
I have, indeed.

As previously stated, the problem is completely resolved- but only when the Roboto font is selected as default.

**Comment by klampferer** [comment]
emojione-android.ttf doesn't seem to be working on CentOS 7.5.1804, fontconfig version 2.10.95, freetype-2.4.11-15.
`fc-validate -v emojione-android.ttf`
`Unable to open emojione-android.ttf`

Ideas anyone? Thanks
