### ISSUE TITLE
💸 FOSS makes more business sense than restrictive licensing

### ISSUE THREAD

**Issue by sebdeckers** [emojione/emojione#488]
Big fan of EmojiOne as my favourite FOSS emoji suite.

I understand you made the license switch, from Creative Commons CC-BY v4 to a restrictive "freemium" license, to pursue commercial IP licensing revenue. In the words of @thinkrick:

> [💵 or 💀?  Translation: We couldn't pay the bills.](https://twitter.com/mobyceo/status/858025074913423360)

I'd like to make a business case for returning to FOSS, so you can become much richer and the rest of us can enjoy beautiful free (as in freedom) emoji.

## Virtual Goods are a Huge Market

Non-textual communications through emoji, gifs, memes, and other art is now a main stream tool for billions of social media users.

VGs are a proven and scalable monetisation strategy, beyond mere advertising, for communications and social media companies, particularly in markets outside US/UK where ad CPM is very low.

Companies like [Tencent, with QQ messenger, proved 10-15 years ago](https://techcrunch.com/2007/06/20/virtual-goods-the-next-big-business-model/) that VGs are a lucrative monetisation model for social media companies. Today, [LINE (Naver) earns hundreds of millions](https://qz.com/704768/line-sold-268-million-worth-of-stickers-last-year-amid-asias-messaging-boom/) selling VGs to their large user base.

Stateside, Giphy has [150 million MAU (Early 2017)](https://www.feedough.com/how-giphy-works-and-makes-money/) and [$150 million raised](https://www.crunchbase.com/organization/giphy) at [$600 million valuation](https://www.wsj.com/articles/gif-site-giphy-is-valued-at-600-million-1477906202). These numbers more than doubled [from 2016](https://www.rt.com/business/344946-giphy-business-plans-earnings/) to 2017.

To capture this revenue it is not sufficient to sell paid licenses to your artwork. Will all due respect, the commercial value is mostly in the end-user distribution channel, not just the quality of the art.

The Unicode set of emoji is the baseline that every app needs to support. By offering the FOSS emoji in a convenient package you can do the obvious upsell of a rev share marketplace.

![go big or go home](https://media.giphy.com/media/l2Sqb5iNnhVr7Ugnu/giphy.gif)

## Be the Marketplace

EmojiOne should offer tools and infrastructure for 3rd party integrators. Your customers are websites, browsers, chat services, discussion boards, video streaming services, mobile phone telcos, etc. Anyone looking to monetise a user base with text communication.

Your products and services include:

- assets library: hosting, multi resolution, static/animated, etc
- multi-platform UI widgets: various web frameworks, iOS, Android
- account management & payment channels
- partnerships: revenue sharing
- brand management: to protect their trademarks
- content curation: e.g. promotional, age restricted, etc
- publisher marketplace: UGC or partner content (another opportunity for rev share to accelerate the business)

By offering these services, you get lots of partner integrations & end users. That gives you the natural monopoly and self-reinforcing network effect.

## FOSS as Business Development

Embrace freedom, don't fight it.

Leverage "piracy." Let others copy and extend your artwork. Their contributions only strengthen your service. Let them do merchandising. Your brand only gets more exposure.

By adopting the FOSS model you get so much goodwill that 3rd parties do the integration of EmojiOne for you, for free. A company offering paid licenses to yet another emoji set would have to expend more resources on BD and marketing, while you'd get to focus on product (designing more emoji, building better tools, improving marketplace). It's your unfair advantage. **Don't throw it away.**

Right now you probably have an ungodly number of users thanks to integrations into Linux distros, mobile apps, and even Firefox browser (who are desperately looking for a revenue source that isn't search engine advertising). Monetise your success. **Don't throw it away.**

![one shot](https://media.giphy.com/media/gix92l3sEjJYs/giphy.gif)

**Comment by TheLastProject** [comment]
I'm honestly rather disappointed to read about the relicensing as well. While I agree that @sebdeckers' suggestions make a lot of sense, if you are dead set on going the licensing route, is there any reason you couldn't at least use the Creative Commons Attribution ShareAlike license as the "free" option? Being a copyleft license, it doesn't harm the Free Software / Open Source community so badly, yet still gives companies more reasons to purchase a "premium" license, as companies tend to be more afraid of breaching copyleft licenses.

I, myself, will be recommending projects to stay with the old v2 EmojiOne set until a good alternative is discovered, as the new "free" license (which is not Open Source at all) makes EmojiOne rather unusable for inclusion in Free Open Source Software projects, which is a shame, as I very much doubt you would've gotten this big in the first place if not for the FOSS community adopting you as a standard due to the licensing making it pretty much the only reasonable option for FOSS projects.

Ironically, this means that the most common version of your emojis will probably be the v2 version, because many people will not upgrade to the newer versions and many users will associate EmojiOne with the v2 version as it's the version they will most likely see. Assuming newer versions will look better, this is unnecessarily damaging EmojiOne's professional look, likely harming more commercial adoption.

I would like to urge you to please reconsider the restrictive licensing choice you have made, as it is rather damaging to the FOSS community and actively restricting the ability for the FOSS community to use these emojis.

**Comment by thinkrick** [comment]
@sebdeckers 

First, let me just say... I really live for this type of thoughtful and constructive feedback.  I've read your post now a few times, and finally had a solid moment to give the proper reply it deserves.  Thank you for your patience so far.  In the spirit of full disclosure, I'll do my best to be fully transparent. ✨

There's obviously a lot at play when determining the overall direction of the business:

* Financial health of our company (runway), overhead
* Our technical capacity, core competency
* Liberties to current licensing partnerships and agencies
* Responsibilities to our current investors
* Much much more

Some major differences between EmojiOne and other Virtual Goods (VGs) posted in your examples:

* The examples you provided were either centralized platforms involving 10's of millions of daily users.  Indirectly we may be reaching or exceeding these numbers, but no way to monetize visitors we have zero direct exposure to.
* There's for sure demand for emoji in all kinds of services, but simply no proof there is enough premium value from side revenue such as custom emoji, animated gifs, integration tools etc.
* A good long term comparison might be FontAwesome, which we feel our new licensing model compares well to.

What we learned by offering the most freedom-based Creative Commons license in EmojiOne v1, v2...

* Developing and maintaining an emoji set is technically very challenging and financially very costly; even if we stuck to just maintaining the art files (we offer much more than this).
* Besides our Browser Extensions (which are successful because of the software), there's little daily active users to monetize from.
* If we found or developed a side revenue model that worked, we would/could have kept the license free and open.  Not saying there isn't one, but we weren't successful at proving one.
* We were losing a lot of money, and making companies a lot of money.  The goal is for everyone to benefit, and needed to look after our own well being.

In the end, the open source license wasn't sustainable.  It didn't make any business sense, and our product quality would suffer and most likely die.  The end goal is to **keep as much free as possible**, while leaving us some room for revenue to sustain our future.  Our [free license](https://www.emojione.com/developers/free-license) still gives individuals and businesses the ability to use our emoji pngs in a similar way as before.  We still service major platforms (like Verizon, Slack, Discourse, Kik) at no charge, and hope to offer free API emoji services to major digital platforms.  I absolutely agree with you that wider reach is the key, and letting our providers do all the marketing for us.

So far, the new licensing structure is working how we had hoped.  We expected a lot of pushback, but thankfully it's been pretty minimal.  I can't blame anyone for thinking _there has to be a better way_... but unless you're sitting in the driver's seat, it's simply not that easy.  With the added revenue, we should be able to re-invest more money to improve our designs; build software to improve our reach; and maintain a small sales force to seek the grand partnerships that will put our brand on the map.

I love this type of feedback, and hope we can continue to find other creative ways to monetize.  As a product creator, I ultimately WANT to see our designs in the hands of more people not less.  We're working on a lot more content, and can't wait to get them in the hands of end users.  In the meantime, look for EmojiOne 3.1 to be released in June.  The designs are spectacular!  💖
