### ISSUE TITLE
emojione.emojiSize not working (3.0.3)

### ISSUE THREAD

**Issue by mroftalp** [emojione/emojione#504]
Setting `emojione.emojiSize = '64'` does not work the CDN link is still using 32.

**Comment by caseyahenson** [comment]
Thanks for pointing that out! We'll get a fix out soon but in the mean time you can set the path for 64s with `emojione.imagePathPNG = 'https://cdn.jsdelivr.net/emojione/assets/3.0/png/64/'`, and that should get you what you're looking for.

**Comment by mroftalp** [comment]
@caseyahenson Yes, I have used that in the meantime. Thank you! Btw when will the Sprite CSS and png assets be available?

**Comment by caseyahenson** [comment]
The assets are now split into their own project. You can access image files via the repo here: https://github.com/Ranks/emojione-assets.

**Comment by caseyahenson** [comment]
This issue is fixed with the release of 3.1. If you specify an emojiSize other than the default (32), the image path to the CDN with the specified size will be returned. If you've installed emojione-assets within your project you can leave the emojiSize as the default and simply specify the local imagePathPNG, including size within the path.
