### ISSUE TITLE
update fonts to emoji 5.0 

### ISSUE THREAD

**Issue by qwertygc** [emojione/emojione#524]
Hello !
I would like know if the fonts will be update to integrate new emojis (5.0). It's pratically font @font-face.

Regards

**Comment by caseyahenson** [comment]
@qwertygc we got those updated files from @vxbakerxv last week and just got the apple font files put up today.

He also put together an android file:
http://www.mediafire.com/file/diixk1eskpkxwp7/EmojiOne+3.1+Android-Noto.zip

@mitchtalmadge @maximbaz or anybody else working on the 3.0 font, would you be able to test that 3.1 font out?

**Comment by maximbaz** [comment]
The font has new emojis, but the toned emojis are not working:

![image](https://user-images.githubusercontent.com/1177900/27806177-61096bd4-6039-11e7-809b-4eec18e010c5.png)

I'll play with the [repo](https://github.com/mxalbert1996/emojione-android) that @mxalbert1996 shared last time, maybe I can build a better font - I'll update soon whether I am succeeding or not.

**Comment by maximbaz** [comment]
With [a couple of changes](https://github.com/maximbaz/emojione-android) I made that code compile the font on my Linux, unfortunately the font I built has exactly the same issues: all new toned/man/woman emojis coming with 3.1 update are not properly rendered.

I can see LigatureSets seemingly correctly defined for the new emojis, and the assets are there. But something must be missing, why else all other toned/man/woman emojis from previous versions being rendered correctly.

Need some fresh ideas... @mxalbert1996, @vXBaKeRXv, @MitchTalmadge: any thoughts what could be missing? 

I'm wondering if this is simply because @mxalbert1996's scripts are based on noto-emoji repo, and those guys themselves don't have the new glyphs yet in their font? 🤔

**Comment by mxalbert1996** [comment]
@maximbaz Actually the scripts detect ligatures from filenames so it doesn't matter whether noto-emoji supports Emoji 5.0. The problem is the filenames. For example, Woman Mage (🧙‍♀️) should be `U+1F9D9` + ‍`U+200D` + `U+2640` where `U+200D` is the Zero Width Joiner, thus the filename of the glyph should be `1f9d9-200d-2640`, but the actual filename in EmojiOne is `1f9d9-2640`. I manually modified the filenames and now [the font](https://raw.githubusercontent.com/mxalbert1996/emojione-android/master/fonts/EmojiOne.ttf) displays well at least in [Font Book](https://www.microsoft.com/en-us/store/p/font-book/9n2b7zh09dt8) on Windows.
![EmojiOne 3.1](https://user-images.githubusercontent.com/9391933/27856779-1f68b69a-61aa-11e7-80dd-5c63eee82dcf.png)
However on my Android 7.1.2 toned emojis in Emoji 5.0 don't display well and the same problem exists even with official Noto Emoji from Android O so I consider it as an Android problem. You can test it on your Linux. And if anyone has Android O devices please test it.

**Comment by maximbaz** [comment]
Thanks, I'll look more in the evening. It should be easy to add an extra rename task in the build, there's [emojione-assets/emoji.json](https://raw.githubusercontent.com/emojione/emojione-assets/master/emoji.json) which defines the naming of every emoji. 

However, for example for `woman mage` this is the definition from the file: `"base":"1f9d9-2640","output":"1f9d9-200d-2640-fe0f"`, so I think the file should be named either with two codes or with four.

**Comment by mxalbert1996** [comment]
@maximbaz No, `U+FE0F` is a control character which tells the rendering system to render the glyph as colored instead of monochrome and it shouldn't be included in the font file.

**Comment by maximbaz** [comment]
I had a chance to test a little bit, I don't think renaming is a correct thing to do... In fact, with your latest font emojis from previous releases broke too...

These are some emojis displayed with the font that I compiled from your repo, no renaming:

![image](https://user-images.githubusercontent.com/1177900/27863702-adcac064-618b-11e7-98e4-ac4b12c38976.png)

These are the same emojis displayed with the font that you've attached above, with renaming:

![image](https://user-images.githubusercontent.com/1177900/27863718-b992c63a-618b-11e7-97df-e46dce8b0681.png)

And this is how the current emojione-android.ttf 3.0 in this repo is rendering them:

![image](https://user-images.githubusercontent.com/1177900/27863795-0e53bb02-618c-11e7-851f-3e9d61dcb341.png)

**Comment by mxalbert1996** [comment]
@maximbaz Actually this is the expected behavior. According to [Unicode](http://unicode.org/emoji/charts/full-emoji-list.html), 🏌️‍♀️ should be `U+1F3CC` + `U+200D` + `U+2640`. The `U+200D` is necessary, otherwise it'll be rendered as two glyphs. You can try using other emoji fonts and the result should be the same.

**Comment by maximbaz** [comment]
No, I know that, I guess I didn't explain myself properly.

Each of these complex glyphs that you see above actually has `U+200D` in them. For example `woman golfing` above is written as `U+1F3CC + U+FE0F + U+200D + U+2640 + U+FE0F`. I can also verify that with multiple ways, I cannot select or remove part of it, I can also copy-paste the emoji in python and run `len("🏌️‍♀️")` and the result will be 5.

The thing is, when emoji is written on the page, the old font correctly renders it as one glyph with a woman playing the golf. The font that you built with renaming suddenly _renders_ it like two separate emojis, seemingly as two characters. Although I still cannot for example select or remove part of it, it is one character from app's perspective.

**Comment by mxalbert1996** [comment]
@maximbaz That is weird, for on my Android phone there isn't this problem.
![screenshot_20170705-213707](https://user-images.githubusercontent.com/9391933/27864648-5c89aeb0-61ca-11e7-8f00-c3086225fdf0.png)
Have you tried using another font such as official Noto Emoji?

**Comment by maximbaz** [comment]
Hey I think you helped me discover a bug in that app itself - I'll deal with it separately.

Looking at emojipedia in Chrome, the same page as you, your latest font renders these fine:

![image](https://user-images.githubusercontent.com/1177900/27865312-6aa5e474-6192-11e7-8e55-755d4fa8bd33.png)

But the problem with emoji-5.0 still persists, even with your new font with renaming... Could you show me a screenshot how this page looks on your phone? 

http://emojipedia.org/emoji-5.0/

You said your phone has issues with toned emojis, lets focus on gender emojis then. Scroll to Genie/Zombie section. This is my output:

![image](https://user-images.githubusercontent.com/1177900/27865402-b90e93e0-6192-11e7-9096-914f4dfb3016.png)

Shouldn't be like that... 🤔

**Comment by mxalbert1996** [comment]
@maximbaz Exactly the same as yours.

**Comment by maximbaz** [comment]
Hm, the chances are small that there's a bug in Android and Linux that prevent rendering only these particular emojis... I'd rather believe something else is wrong with our font 🤔

**Comment by mxalbert1996** [comment]
@maximbaz I've tested on Ubuntu 17.04 and it displays without problem.
![2017-07-06 01-20-23](https://user-images.githubusercontent.com/9391933/27874288-f4fcde1e-61e9-11e7-92b4-ad572ff04dfa.png)
Also as I mentioned before even the official Noto Color Emoji from Android O doesn't display well on Android N.
Thus I think it's obviously a system problem.

**Comment by maximbaz** [comment]
First of all I am impressed that this font works in Firefox, I was under the impression that it uses some technology supported only by Chrome.

But yeah, I just installed Firefox and I totally reproduce your results. So it's a bug in Chrome... :man_facepalming:  

Also, in Firefox all glyphs are rendered correctly with either of the fonts, the one that didn't do any renaming and the one that does it. What is the difference then, do you know? Do we need to ask here for renaming emoji files, or it really doesn't matter?

**Comment by maximbaz** [comment]
To clarify, when we _type_ emojis we definitely should use full code points list, that's not being questioned. The question is, fonts built with or without renaming seem to be _rendering_ those emojis identically correctly... So is there a need to ask to rename image files?

**Comment by mxalbert1996** [comment]
@maximbaz It matters because the old font can cause unexpected behaviors. For example I want to show 2 separated emojis 👨👩 but with the old font it's possible because it automatically converts it to 👨‍👩.

**Comment by maximbaz** [comment]
And I can reproduce this 🙂

Old font, image files are named incorrectly:

![image](https://user-images.githubusercontent.com/1177900/27875840-fa590552-61b4-11e7-8b64-541b5751c885.png)

New font, with image files renamed:

![image](https://user-images.githubusercontent.com/1177900/27875789-c5f59852-61b4-11e7-9fa5-58836108a722.png)


Thank you so much @mxalbert1996, I learned a lot today!

**Comment by maximbaz** [comment]
Last question @mxalbert1996, did you rename all the incorrectly named files, or only some of them? Do you have an easy way (script) to rename them to a correct format?

**Comment by mxalbert1996** [comment]
I renamed all. The method is, for all filenames, replace
`-2640` with `-200d-2640`,
`-2642` with `-200d-2642`,
`-1f308` with `-200d-1f308`,
`-1f5e8` with `-200d-1f5e8`,
`-1f33e` with `-200d-1f33e`,
`-1f373` with `-200d-1f373`,
`-1f393` with `-200d-1f393`,
`-1f3a4` with `-200d-1f3a4`,
`-1f3a8` with `-200d-1f3a8`,
`-1f3eb` with `-200d-1f3eb`,
`-1f3ed` with `-200d-1f3ed`,
`-1f4bb` with `-200d-1f4bb`,
`-1f4bc` with `-200d-1f4bc`,
`-1f527` with `-200d-1f527`,
`-1f52c` with `-200d-1f52c`,
`-1f680` with `-200d-1f680`,
`-1f692` with `-200d-1f692`,
`-2695` with `-200d-2695`,
`-2696` with `-200d-2696`,
`-2708` with `-200d-2708`,
`-1f466` with `-200d-1f466`,
`-1f467` with `-200d-1f467`,
`-1f468` with `-200d-1f468`,
`-1f469` with `-200d-1f469`.

**Comment by maximbaz** [comment]
Once again, thank you!

**Comment by vXBaKeRXv** [comment]
Good stuff! I like reading this type of things. I try to stick with stock releases and just rebuild the table that holds the images. Use the right data made in the font to make the correct image names. If the system or program not setup to handle the new data in font you can run into problems, lig or not.

If FontTools ever adds support for "morx" table we could see tools similar to googles noto emoji project to make apples sbix fonts using a set of image names.  I would recommend noto emoji to switch to apples short naming method because its faster and clear. 


https://github.com/vXBaKeRXv/EmojiFontData
I made a script in python to grab and join the info and save to .txt doc. I recently started using these created lists from font data to auto rename images to make a new sbix table. Need to fix the latest emojione apple font because I added support for wrestlers skins like android but image names in assests didn't match. Human errors are hard to wipe out lol.  

Check out the ZWJ and Variation selector in apples emoji, very cleaver.  
iOS they still use PUA info that's connect to sbix for backwards support.  I just don't have that info up, but its neat to see also.

**Comment by mxalbert1996** [comment]
I just tried Android Emulator and... I don't know what Google's thinking but even the stock Android O cannot properly display toned emojis in Emoji 5.0.
![screenshot_1499312674](https://user-images.githubusercontent.com/9391933/27894833-8f43971a-6249-11e7-9d7b-578bff99b221.png)

**Comment by maximbaz** [comment]
I think it's a bug in Chromium for all platforms, as a wild guess, look [here](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/platform/text/CharacterEmoji.cpp?l=137), the emoji list ends with `1F9C0`, but all the new emojis like mage (`1F9D9`) or genie (`1F9DE`) are beyond that.

I found this link [here](https://bugs.chromium.org/p/chromium/issues/detail?id=613875), which is a bug reported a year ago for Unicode 9 emojis, perhaps it's time to file a similar bug for Unicode 10 emojis 😄

**Comment by mxalbert1996** [comment]
@maximbaz I found that [such issue](https://bugs.chromium.org/p/chromium/issues/detail?id=719963) already exists. However it is now blocked by [this issue](https://bugs.chromium.org/p/chromium/issues/detail?id=719965), which means Chromium currently doesn't support the new subdivision-flag feature in Emoji 5.0, and Emoji 5.0 support will be implemented after that.

**Comment by maximbaz** [comment]
@mxalbert1996 I was trying to reverse engineer how you came up with that list, I think I found two more pairs where replacement is needed. Could you confirm?

```
-2764 with -200d-2764  (example: 1F469 200D 2764 FE0F 200D 1F468 couple with heart: woman, man)
-1f48b with -200d-1f48b (example: 1F469 200D 2764 FE0F 200D 1F48B 200D 1F468 kiss: woman, man)
```

And I should mention for completeness that the replacement could be required multiple times for a given emoji name.

**Comment by mxalbert1996** [comment]
@maximbaz You are right. I didn't notice them.

**Comment by caseyahenson** [comment]
Hey guys, really nice work on this! I'll get that new file added to the repo. @maximbaz I'll also leave a comment in the issue you added to emojione-assets but to summarize, we'll be adding the appropriate code point into the emoji.json file which will then still need to be mapped, but at least the renaming logic won't be at the user's discretion.

**Comment by maximbaz** [comment]
That will be helpful - thanks 🙂
