### ISSUE TITLE
Version 3.1.1 not available in jsdelivr cdn

### ISSUE THREAD

**Issue by bl4ze** [emojione/emojione#534]
Links to version 3.1.1 mentioned in INSTALLATION.MD are not available on CDN.
[here](https://github.com/emojione/emojione/blob/master/INSTALLATION.md)

https://cdn.jsdelivr.net/emojione/3.1.1/lib/js/emojione.min.js
https://cdn.jsdelivr.net/emojione/3.1.1/extras/css/emojione.min.css

**Comment by MartinKolarik** [comment]
The correct link for new versions is https://cdn.jsdelivr.net/npm/emojione/ but it doesn't work because emojione packages are too big for our new endpoints (170 MB). 165 MB of that are font files under `extras/fonts`.

@emojione would it be possible for you guys to also make releases without those large files (e.g. under `emojione-lite` on npm)?

**Comment by kevinranks** [comment]
@MartinKolarik we could move the font files to our [emojione-assets](https://github.com/emojione/emojione-assets) repo, as long as the community is on board with that....

**Comment by MartinKolarik** [comment]
@kevinranks that sounds good to me 👍

**Comment by kevinranks** [comment]
@MartinKolarik Can the latest 3.1.2 release be published on jsdelivr now?

**Comment by MartinKolarik** [comment]
Yep, it's there: https://cdn.jsdelivr.net/npm/emojione@3.1.2/ 👍

**Comment by kevinranks** [comment]
Oh I see, you guys released your new backend. So the urls need to be updated. I'll update the notes in the docs here. Thanks!

**Comment by MartinKolarik** [comment]
Yes, please use the new `/npm/` links for all new versions.
