### ISSUE TITLE
TTF font with EmojiOne name for using in Linux

### ISSUE THREAD

**Issue by morealaz** [emojione/emojione#558]
Currently we have a ttf font for android which its font name is **Noto Color Emoji**, so that it could replace default android font. we can use it under linux, but it can not be used simultaneously with actual  **Noto Color Emoji** font. Can we have a ttf font with **EmojiOne** font name like other version of emojione fonts?

**Comment by maximbaz** [comment]
It is certainly possible, but there are quite a few moving parts. If you or someone else wants to tackle this problem, here's what to do:

1. The font name is hardcoded in [a font template](https://github.com/maximbaz/emojione-android/blob/411a978944c89f1c7c453e67276b09d8666f4eae/EmojiOne.tmpl.ttx.tmpl#L232-L253), so one would need to write a simple script to adjust the font names (a few `sed` calls should suffice). You can put the script in that same repo.
2. Create a new make target in [makefile](https://github.com/maximbaz/emojione-android/blob/master/Makefile) that will run this script before compiling the emoji.
3. That repo is used in a [docker image](https://github.com/maximbaz/docker-emojione-fonts-build) for compiling the font, today it just [executes make without parameters](https://github.com/maximbaz/docker-emojione-fonts-build/blob/5ad99fa28feaf367d7869121a4831b5b93eb694f/build.sh#L19-L20), you can copy-paste the same two lines below and in addition to compiling android font also compile linux font (by calling `make` with extra goal that you created on step 2).
4. And finally extend the [travis job](https://github.com/emojione/emojione-assets/blob/3d86ce42b452924139902868f6073e6393491aa2/.travis.yml#L26) with the new `emojione-linux.ttf` so that it is published automatically on the next release.
